import type { ContactFormInput } from '../pages/ContactPage';

/** Message field enforces minlength=50/maxlength=500 - keep fixtures comfortably inside that range. */
export function validContactSubmission(
  overrides: Partial<ContactFormInput> = {},
): ContactFormInput {
  return {
    name: 'QA Automation',
    email: 'qa-automation@example.com',
    company: 'Playwright Framework',
    message:
      'This is an automated end-to-end test submission generated by the Playwright test suite. ' +
      'It is intercepted before reaching the real endpoint and never delivered.',
    ...overrides,
  };
}

export const invalidEmails = [
  'not-an-email',
  'missing-domain@',
  '@missing-local.com',
  'spaces are bad@example.com',
];

export const xssProbe = '<script>window.__xssFired = true;</script>';
